### ISSUE TITLE
Error in getDLLRegisteredRoutines.DLLInfo

### ISSUE THREAD

**Issue by 2005m** [tidyverse/readxl#520]
Hi,

When I try to check and build your package in RStudio I get the following message.

```
==> roxygen2::roxygenize('.', roclets = c('rd', 'collate', 'namespace'))

Loading readxl
Error in getDLLRegisteredRoutines.DLLInfo(dll, addNames = FALSE) : 
  must specify DLL via a "DLLInfo" object. See getLoadedDLLs()
Calls: suppressPackageStartupMessages ... assignNativeRoutines -> getDLLRegisteredRoutines.DLLInfo
Execution halted

Exited with status 1.
```
Am I missing something ?
I am on windows and I have build the libxls library.

Thank you

**Comment by jennybc** [comment]
What exact steps got you to this point?

**Comment by 2005m** [comment]
Hi,

Thank you for you reply.

**Step 1:** (not needed to replicate the issue)
--------------------------------------------------

-Under windows, I am using msys2 mingw 64 (a good link if you need more information on it : [link](https://github.com/orlp/dev-on-windows/wiki/Installing-GCC--&-MSYS2) ) to install libxls. In the terminal I typed the following command one after the other:

git clone https://github.com/evanmiller/libxls.git
cd libxls
./configure && make -j4
make install

**Step 2:**
--------------------------------------------------

-Still in msys2 mingw 64, I type the following command:

$ git clone https://github.com/tidyverse/readxl.git
Cloning into 'readxl'...
remote: Enumerating objects: 31, done.
remote: Counting objects: 100% (31/31), done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 3283 (delta 7), reused 11 (delta 4), pack-reused 3252
Receiving objects: 100% (3283/3283), 8.43 MiB | 1.26 MiB/s, done.
Resolving deltas: 100% (2223/2223), done.
Checking out files: 100% (237/237), done.

-Then I open RStudio and open the R project file "readxl"
-In the tab "Build", I click the button "Check" and you will get the message I pasted in my first post.

For your information I am running R-3.5.1.
Please let me know if you need anything else.

Best regards

**Comment by jennybc** [comment]
If you just want to use readxl, you should do so via the usual `install.packages("readxl")`, which will install a prebuilt binary.

If you want to develop / extend readxl, then ... can you assure me that you're fully set up for R development work with compiled code already? Can you successfully build other R packages containing compiled code?

In any case, you will never be building the libxls library on its own, for use with readxl.

**Comment by 2005m** [comment]
I want to develop/extend. How do I make sure that my set up is fine?
devtools and rtools are installed. I have some packages that use Rcpp and contain C/C++ code which work fine.

Were you able to reproduce the error?

**Comment by jennybc** [comment]
I haven't tried today on my Windows VM but readxl is being built (successfully atm) upon every comment on Windows via AppVeyor:

https://ci.appveyor.com/project/tidyverse/readxl/history

**Comment by 2005m** [comment]
For your information, i have no issue installing the package with devtools::install from my cloned git version. However building the package or checking the package inside RStudio like I described it produce an error. Maybe it is linked to RStudio?

**Comment by jennybc** [comment]
RStudio calls devtools itself (albeit sometimes with different arguments). Or, at least, it can. You might want to confirm that "Use devtools package functions if available" is checked in the *Project Options > Build Tools*.

You can try `devtools::check()` in the R console in a shell to shed some light on whether RStudio has anything to do with what you're seeing.

You also might want to show me your session info re: devtools and related packages, i.e. `devtools::session_info("devtools")`.

**Comment by 2005m** [comment]
I confirm that "Use devtools package functions if available" is checked. `devtools::check` runs fine with no error message.

Here is the output of the command `devtools::session_info("devtools")`

````
> devtools::session_info("devtools")
- Session info ------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.5.1 (2018-07-02)
 os       Windows 7 x64 SP 1          
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_United States.1252  
 ctype    English_United States.1252  
 tz       Europe/London               
 date     2018-11-24                  

- Packages ----------------------------------------------------------------------------------
 package     * version date       lib source        
 assertthat    0.2.0   2017-04-11 [1] CRAN (R 3.5.1)
 backports     1.1.2   2017-12-13 [1] CRAN (R 3.5.0)
 base64enc     0.1-3   2015-07-28 [1] CRAN (R 3.5.0)
 callr         3.0.0   2018-08-24 [1] CRAN (R 3.5.1)
 cli           1.0.1   2018-09-25 [1] CRAN (R 3.5.1)
 clipr         0.4.1   2018-06-23 [1] CRAN (R 3.5.1)
 clisymbols    1.2.0   2017-05-21 [1] CRAN (R 3.5.1)
 crayon        1.3.4   2017-09-16 [1] CRAN (R 3.5.1)
 curl          3.2     2018-03-28 [1] CRAN (R 3.5.1)
 desc          1.2.0   2018-05-01 [1] CRAN (R 3.5.1)
 devtools      2.0.1   2018-10-26 [1] CRAN (R 3.5.1)
 digest        0.6.18  2018-10-10 [1] CRAN (R 3.5.1)
 fs            1.2.6   2018-08-23 [1] CRAN (R 3.5.1)
 gh            1.0.1   2017-07-16 [1] CRAN (R 3.5.1)
 git2r         0.23.0  2018-07-17 [1] CRAN (R 3.5.1)
 glue          1.3.0   2018-07-17 [1] CRAN (R 3.5.1)
 httr          1.3.1   2017-08-20 [1] CRAN (R 3.5.1)
 ini           0.3.1   2018-05-20 [1] CRAN (R 3.5.1)
 jsonlite      1.5     2017-06-01 [1] CRAN (R 3.5.1)
 magrittr      1.5     2014-11-22 [1] CRAN (R 3.5.1)
 memoise       1.1.0   2017-04-21 [1] CRAN (R 3.5.1)
 mime          0.6     2018-10-05 [1] CRAN (R 3.5.1)
 openssl       1.1     2018-11-15 [1] CRAN (R 3.5.1)
 pkgbuild      1.0.2   2018-10-16 [1] CRAN (R 3.5.1)
 pkgload       1.0.2   2018-10-29 [1] CRAN (R 3.5.1)
 prettyunits   1.0.2   2015-07-13 [1] CRAN (R 3.5.1)
 processx      3.2.0   2018-08-16 [1] CRAN (R 3.5.1)
 ps            1.2.1   2018-11-06 [1] CRAN (R 3.5.1)
 R6            2.3.0   2018-10-04 [1] CRAN (R 3.5.1)
 rcmdcheck     1.3.2   2018-11-10 [1] CRAN (R 3.5.1)
 Rcpp          1.0.0   2018-11-07 [1] CRAN (R 3.5.1)
 remotes       2.0.2   2018-10-30 [1] CRAN (R 3.5.1)
 rlang         0.3.0.1 2018-10-25 [1] CRAN (R 3.5.1)
 rprojroot     1.3-2   2018-01-03 [1] CRAN (R 3.5.1)
 rstudioapi    0.8     2018-10-02 [1] CRAN (R 3.5.1)
 sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 3.5.1)
 usethis       1.4.0   2018-08-14 [1] CRAN (R 3.5.1)
 whisker       0.3-2   2013-04-28 [1] CRAN (R 3.5.1)
 withr         2.1.2   2018-03-15 [1] CRAN (R 3.5.1)
 xopen         1.0.0   2018-09-17 [1] CRAN (R 3.5.1)

[1] C:/Users/M/Documents/R/win-library/3.5
[2] C:/Program Files/R/R-3.5.1/library
````
I think the issue is coming from the version of RStudio I am using, i.e **Version 1.2.1090**. When I use RStudio **Version 1.1.463** and I click the "Check" button the command `devtools::check()` is executed, however when I use **Version 1.2.1090** the command `roxygen2::roxygenize('.', roclets = c('rd', 'collate', 'namespace'))` is executed and I get an error. Not sure to understand why the command is not the same from one version of RStudio to the other as all the build options are exactly the same.

Not sure but looks like a bug on the new version of RStudio?
If it is case the case I am sure you will report it and can close the issue.

@jennybc , thank you very much for you help and have a nice week end.

**Comment by jennybc** [comment]
The current Preview version of RStudio is v1.2.1139-1:

https://www.rstudio.com/products/rstudio/download/preview/

I think upgrading to that is a good first step, regardless.

**Comment by jennybc** [comment]
I think you should upgrade RStudio (Preview is now at v1.2.1153-1).

Hopefully all will be well. Report back if not. But I suspect we'll chalk this up to you having an unlucky Preview version and this is now fixed.

**Comment by 2005m** [comment]
I tried with version 1.2.1163 and still the same, i.e.  like version 1.2.1090 and not like version 1.1.463.

**Comment by ssnn-airr** [comment]
This seems related to klutometis/roxygen#822. As suggested there, try running `pkgbuild::compile_dll()` before building.

**Comment by jennybc** [comment]
I am seeing this as well in my Windows VM, via RStudio *Build > Check* and in the console via `devtools::check()`.

![readxl-check-fail](https://user-images.githubusercontent.com/599454/49851669-adf16400-fd96-11e8-97d3-aae4c9233683.PNG)

**Comment by jennybc** [comment]
Seems like this: https://github.com/klutometis/roxygen/issues/822

I was able to document and check the package by executing `devtools::load_all()` once.

**Comment by maurolepore** [comment]
I get a similar error when setting up Rcpp on Windows then trying to document. 

Precisely the ploblem is exposed by `, .registration = TRUE` as shown below. Removing  `, .registration = TRUE` allows me to document, but then I guess Rcpp won't work? 

I don't get the error at all on rstudio.cloud (on Linux?)

(It's my first time setting up Rcpp so I am likely doing something very silly -- sorry.)

(R/abc-package.R)
```R
#' @keywords internal
"_PACKAGE"

# The following block is used by usethis to automatically manage
# roxygen namespace tags. Modify with care!
## usethis namespace: start
#' @useDynLib abc, .registration = TRUE
#' @importFrom Rcpp sourceCpp
## usethis namespace: end
NULL

```

<details>
  <summary>Here is how I get to the problem after creating a new package</summary>

```R

R version 3.5.3 (2019-03-11) -- "Great Truth"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> usethis::use_roxygen_md()
✔ Setting active project to 'C:/Users/LeporeM/abc'
✔ Setting Roxygen field in DESCRIPTION to 'list(markdown = TRUE)'
✔ Setting RoxygenNote field in DESCRIPTION to '6.1.1'
● Run `devtools::document()`
> devtools::document()
Updating abc documentation
Writing NAMESPACE
Loading abc
> usethis::use_package_doc()
✔ Writing 'R/abc-package.R'
> devtools::document()
Updating abc documentation
Loading abc
Writing abc-package.Rd
> usethis::use_rcpp()
✔ Creating 'src/'
✔ Adding '*.o', '*.so', '*.dll' to 'src/.gitignore'
✔ Adding '@useDynLib abc, .registration = TRUE' to 'R/abc-package.R'
● Run `devtools::document()` to update 'NAMESPACE'
✔ Adding 'Rcpp' to LinkingTo field in DESCRIPTION
✔ Adding 'Rcpp' to Imports field in DESCRIPTION
✔ Adding '@importFrom Rcpp sourceCpp' to 'R/abc-package.R'
● Run `devtools::document()` to update 'NAMESPACE'
> devtools
Error: object 'devtools' not found
> devtools::document()
Updating abc documentation
Writing NAMESPACE
Loading abc
Error in getDLLRegisteredRoutines.DLLInfo(dll, addNames = FALSE) : 
  must specify DLL via a “DLLInfo” object. See getLoadedDLLs()
Call `rlang::last_error()` to see a backtrace
```
</details>

<details>
  <summary>Session info</summary>

``` r
sessioninfo::session_info()
#> - Session info ----------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.5.3 (2019-03-11)
#>  os       Windows 10 x64              
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  English_United States.1252  
#>  ctype    English_United States.1252  
#>  tz       America/New_York            
#>  date     2019-04-18                  
#> 
#> - Packages --------------------------------------------------------------
#>  package     * version date       lib source        
#>  assertthat    0.2.1   2019-03-21 [1] CRAN (R 3.5.3)
#>  cli           1.1.0   2019-03-19 [1] CRAN (R 3.5.3)
#>  crayon        1.3.4   2017-09-16 [1] CRAN (R 3.5.2)
#>  digest        0.6.18  2018-10-10 [1] CRAN (R 3.5.2)
#>  evaluate      0.13    2019-02-12 [1] CRAN (R 3.5.2)
#>  highr         0.8     2019-03-20 [1] CRAN (R 3.5.3)
#>  htmltools     0.3.6   2017-04-28 [1] CRAN (R 3.5.2)
#>  knitr         1.22    2019-03-08 [1] CRAN (R 3.5.2)
#>  magrittr      1.5     2014-11-22 [1] CRAN (R 3.5.2)
#>  Rcpp          1.0.1   2019-03-17 [1] CRAN (R 3.5.3)
#>  rmarkdown     1.12    2019-03-14 [1] CRAN (R 3.5.2)
#>  sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 3.5.2)
#>  stringi       1.4.3   2019-03-12 [1] CRAN (R 3.5.3)
#>  stringr       1.4.0   2019-02-10 [1] CRAN (R 3.5.2)
#>  withr         2.1.2   2018-03-15 [1] CRAN (R 3.5.2)
#>  xfun          0.6     2019-04-02 [1] CRAN (R 3.5.3)
#>  yaml          2.2.0   2018-07-25 [1] CRAN (R 3.5.2)
#> 
#> [1] C:/Users/LeporeM/Documents/R/win-library/3.5
#> [2] C:/Users/LeporeM/Documents/R/R-3.5.3/library
```

</details>

**Comment by jennybc** [comment]
What if you execute `devtools::load_all()` (or `pkgbuild::compile_dll()`)? Then try to `document()`.

**Comment by maurolepore** [comment]
(Thanks for your help and patience. I understand my problem has nothing to do with readxl.)

Still failing:

```R
Restarting R session...

> devtools::load_all()
Loading abc
Error in getDLLRegisteredRoutines.DLLInfo(dll, addNames = FALSE) : 
  must specify DLL via a “DLLInfo” object. See getLoadedDLLs()
Call `rlang::last_error()` to see a backtrace
> pkgbuild::compile_dll()
> devtools::document()
Updating abc documentation
Loading abc
Error in getDLLRegisteredRoutines.DLLInfo(dll, addNames = FALSE) : 
  must specify DLL via a “DLLInfo” object. See getLoadedDLLs()
Call `rlang::last_error()` to see a backtrace
```

**Comment by jennybc** [comment]
What is the state of `#' @useDynLib abc, .registration = TRUE` in all of the above?

But this is really not my specialty so probably better to take this conversation to Slack or community.rstudio.com.

**Comment by maurolepore** [comment]
Thanks, will do!
